spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  mail:
      host: smtp.qq.com
      username: 3473407244@qq.com
      password: dmpqcsokaifldbbc
      default-encoding: UTF-8
      port: 465
      properties:
        mail:
                smtp:
                  auth: true
                  socketFactory:
                    port: 465
                    class: javax.net.ssl.SSLSocketFactory
                    fallback: false
                  starttls:
                    enable: true
                    required: true






