spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drbox?useUnicode=true&characterEncoding=utf-8
    username: root
    password: dengdaiwushi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.lxy11: debug
  file: log/drbox-dev.log







